{-----------------------------------------------------------------------------
 Program:   kinode01
 Unit Name: kinode01.inc
 Author:    n0mad
 Version:   1.2.8.x
 Creation:  01.03.2004
 Purpose:   Define conditionals
 History:
-----------------------------------------------------------------------------}
//{$DEFINE No_Debug}
{$UNDEF No_Debug}

//{$DEFINE No_Jcl_Debug}
{$UNDEF No_Jcl_Debug}

//{$DEFINE No_Eureka_Debug}
{$UNDEF No_Eureka_Debug}

{$DEFINE Debug_Level_1}
{$DEFINE Debug_Level_2}
{$DEFINE Debug_Level_3}
{$DEFINE Debug_Level_4}
{$DEFINE Debug_Level_5}
{$DEFINE Debug_Level_6}
{$DEFINE Debug_Level_7}
{$DEFINE Debug_Level_8}
{$DEFINE Debug_Level_9}

//{$UNDEF Debug_Level_1}
//{$UNDEF Debug_Level_2}
//{$UNDEF Debug_Level_3}
//{$UNDEF Debug_Level_4}
//{$UNDEF Debug_Level_5}
//{$UNDEF Debug_Level_6}
{$UNDEF Debug_Level_7}
{$UNDEF Debug_Level_8}
{$UNDEF Debug_Level_9}

{$DEFINE Use_Local_Lib}
