{-----------------------------------------------------------------------------
 Unit Name  :  Bugger.inc
    Author  :  n0mad
   Version  :  (B) 2004.11.05.02
  Creation  :  04.04.2003
   Purpose  :  Define debug conditionals
   Program  :  Common type
   History  :
-----------------------------------------------------------------------------}
//{$DEFINE NO_DEBUG}

{$UNDEF DEBUG_Module_Start_Finish}

{$UNDEF DEBUG_Module_Default_Set}

//{$UNDEF DEBUG_Module_Final_Section}
